---
info:
  build:
    version: @project.version@
eureka:
  client:
    enabled: true
logging:
  level:
    com.byteworksinc.batchdemo.Application: ERROR
    com.byteworksinc.batchdemo.batch: DEBUG
spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
  batch:
    job:
      enabled: false
  main:
    banner-mode: 'off'
  output:
    ansi:
      enabled: ALWAYS
