info:
  build:
    version: @project.version@
batch:
  cron-expression: '0 23 * * * ?'
eureka:
  client:
    enabled: true
logging:
  level:
    com.byteworksinc.batchdemo.Application: 'INFO'
    com.byteworksinc.batchdemo.batch: 'DEBUG'
spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
  batch:
    job:
      enabled: false
  main:
    banner-mode: 'off'
  output:
    ansi:
      enabled: ALWAYS
